# Generated by Django 3.2.16 on 2022-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'return',
                'managed': False,
            },
        ),
    ]
