# Generated by Django 3.2.16 on 2022-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookD',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('edition', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('publication', models.CharField(max_length=25)),
                ('pages', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'book_d',
                'managed': False,
            },
        ),
    ]
